---
title: "Example of using the simulator"
output: html_document
date: "2024-02-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(plotly)
```


## Capacity fractions example

```{r}
source("capacity_fractions.R")
```

```{r}
# The following snippet will create a table of capacity fractions.
# Two peak moments are defined: 7-9h and 17-23h.
# The first peak moment has no pre- or post slope.
# The second peak moment has a pre slope of 1h and a post slope of 7h.
# This means that it takes 1h for the capacity to go down from max to base capacity,
# and 7h for the capacity to go back from base to max.
capacity_fractions <- create_capacity_fractions_netbewust_laden(as_datetime("2023-12-01"), as_datetime("2025-01-07"), times=list(
  list(floor_start=17, floor_end=23, pre_slope=1, post_slope=7),
  list(floor_start=7, floor_end=9, pre_slope=NULL, post_slope=NULL)
  )) %>%
  filter(date_time >= "2023-12-25", date_time <= "2025-01-08")

capacity_fractions
 
capacity_fractions %>%
  filter(date_time >= "2024-01-01", date_time <= "2024-01-03") %>%
  plot_ly(x=~date_time, y=~value, type="scatter", mode="lines")
```


## Model example

```{r}
source("model.R")
```

```{r}
# We load the sessions table
sessions_path = "data/Input/home_combined/sessions.rds"
sessions <- readRDS(sessions_path)
sessions_week <- get_sessions_week(sessions, "Charging Station")
```

```{r}
source("model.R")

results <- simulate(
  sessions,
  sessions_week,
  n_runs=100,
  year = 2024,
  profile_type = "Charging Station",
  regular_profile = TRUE,
  charging_location = "home",
  n_charging_points = 1,
  seed = 12345
)

results
```

## Elementary analysis

```{r}
results$individual %>%
  filter(run_id == 1) %>%
  plot_ly(x=~date_time, y=~power, type="scatter", mode="lines")

results$aggregated %>%
  mutate(Time = strftime(date_time, "%H:%M")) %>%
  group_by(Time) %>%
  summarise(Power = mean(power)) %>%
  plot_ly(x=~Time, y=~Power)

results$individual %>%
  group_by(run_id) %>%
  # Each interval is 1h/4
  summarise(Energy = sum(power) / 4) %>%
  plot_ly(x=~run_id, y=~Energy, type="bar")
```


## Simulation with Smart Charging

```{r}
source("model.R")

results <- simulate(
  sessions,
  sessions_week,
  n_runs=10,
  year = 2024,
  profile_type = "Charging Station",
  charging_location = "public",
  n_charging_points = 2,
  seed = 12345,
  regular_profile = FALSE,                 # This enables Smart Charging
  capacity_fractions = capacity_fractions  # We use the capacity fractions previously defined
)

results
```

### Elementary analysis with smart charging active

```{r}
results$individual %>%
  filter(run_id == 1) %>%
  plot_ly(x=~date_time, y=~power, type="scatter", mode="lines")

results$aggregated %>%
  mutate(Time = strftime(date_time, "%H:%M")) %>%
  group_by(Time) %>%
  summarise(Power = mean(power)) %>%
  plot_ly(x=~Time, y=~Power)

results$individual %>%
  group_by(run_id) %>%
  # Each interval is 1h/4
  summarise(Energy = sum(power) / 4) %>%
  plot_ly(x=~run_id, y=~Energy, type="bar")
```

